name: Slow tests
on:
  # Run automatically for pull requests
  pull_request:
  # Allow for manual trigger
  workflow_dispatch:
  # Schedule a run once per week
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  lint:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - id: install-pipenv
        name: Install pipenv
        run: |
            python -m pip install --upgrade --no-cache-dir pip
            python -m pip install --no-cache-dir pipenv
        shell: bash

      - id: cache-pipenv
        name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - id: sync-pipfile
        name: Sync pipfile
        run: pipenv sync --dev
        shell: bash

      - id: flake8
        name: Flake8
        run: pipenv run flake8 court_scraper

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - id: install-pipenv
        name: Install pipenv
        run: |
            python -m pip install --upgrade --no-cache-dir pip
            python -m pip install --no-cache-dir pipenv
        shell: bash

      - id: cache-pipenv
        name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - id: sync-pipfile
        name: Sync pipfile
        run: pipenv sync --dev
        shell: bash

      - id: quick-tests
        name: Quick tests
        run: make test

      - id: slow-tests
        name: Slow tests
        run: make test-slow-nocaptcha
