name: Tests
on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: 3.7

      - id: flake8
        name: Flake8
        run: make lint

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v1
        with:
          python-version: ${{ matrix.python }}

      - id: tests
        name: Tests
        run: pipenv run coverage run --source court_scraper -m pytest

      - id: coverage
        name: Coverage
        run: pipenv run coverage report -m
